# config.yaml
data:
  csv_path: "test.csv" 
  batch_size_train: 8
  batch_size_val: 4
  test_size: 0.05
  random_seed: 42

model:
  model_path: "/root/autodl-fs/gemma-2-2b-it"
  max_len: 1024
  lora_r: 16
  lora_alpha: 32
  lora_dropout: 0.05

training:
  epochs: 3
  lr: 1e-5          
  alpha: 0.001
  save_dir: "./gemma2_lora_reward"
  clip_grad: true   
